#include <LiquidCrystal.h> // Incluye la Libreria LiquidCrystal
LiquidCrystal lcd(8, 9, 10, 11, 12, 13); // Crea un Objeto LC. Parametros: (rs, enable, d4, d5, d6, d7)

char * Empresa = "    MB: MAS     ";
int MAS;
void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
lcd.begin(16,2); // Inicializa la interface para el LCD screen, and determina sus dimensiones (ancho y alto) del display
}

void loop() {
  // put your main code here, to run repeatedly:
lcd.setCursor (0,0);
lcd.print("ARDUINO DAY 2019");
lcd.setCursor (0,1);
lcd.print("  Mendoza,ARG");
delay(5000);
lcd.clear();

lcd.setCursor (0,0);
lcd.print(" TE PRESENTO A:");
lcd.setCursor (0,1);
lcd.print(Empresa);
delay(5000);
lcd.clear();
delay(100);

delay(200);
lcd.setCursor (0,0);
lcd.print("Presentado Por:");
lcd.setCursor (0,1);
lcd.print(" Mario Bustillo");
delay(5000);
lcd.clear();
delay(100);

lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("          Medir ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("         Medir e");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("        Medir el");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("       Medir el ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("      Medir el %");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("     Medir el % ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("    Medir el % d");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("   Medir el % de");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("  Medir el % de ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print(" Medir el % de C");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("Medir el % de Co");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("edir el % de Con");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("dir el % de Cont");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("ir el % de Conta");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("r el % de Contam");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print(" el % de Contami");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("el % de Contamin");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("l % de Contamina");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print(" % de Contaminac");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("% de Contaminaci");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print(" de Contaminacio");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("de Contaminacion");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("e Contaminacion");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print(" Contaminacion d");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("Contaminacion de");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("ontaminacion de ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("ntaminacion de u");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("taminacion de un");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("aminacion de un ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("minacion de un E");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("inacion de un En");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("nacion de un Ent");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("acion de un Ento");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("cion de un Entor");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("ion de un Entorno");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("on de un Entorno ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("n de un Entorno C");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print(" de un Entorno Ce");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("de un Entorno Cer");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("e un Entorno Cerr");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print(" un Entorno Cerra");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("un Entorno Cerrad");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("n Entorno Cerrado");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print(" Entorno Cerrado");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("Entorno Cerrado");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("ntorno Cerrado");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("torno Cerrado");
delay(550);
lcd.setCursor (0,0);
lcd.print("    Funcion");
lcd.setCursor (0,1);
lcd.print("orno Cerrado");
delay(550);

lcd.setCursor (0,0);
lcd.print("MB MAC Detecta:");
lcd.setCursor (0,1);
lcd.print("CO, Humo, Metano ");
delay(5000);
lcd.clear();

lcd.setCursor (0,0);
lcd.print("MB MAC Detecta:");
lcd.setCursor (0,1);
lcd.print("  Butano, LPG ");
delay(5000);
lcd.clear();
}

void MB(){
int MB = strlen (MAS);
for (int Char=0; Char<=2; Char++)
{
lcd.setCursor (0,0);
lcd.print(Empresa);
lcd.setCursor (0,1);
lcd.print("       Mindstorm");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("      Mindstorm ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("     Mindstorm B");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("    Mindstorm Bi");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("   Mindstorm Bio");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("  Mindstorm Biol");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print(" Mindstorm Biolo");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("Mindstorm Biolog");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("indstorm Biologi");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("ndstorm Biologic");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("dstorm Biologica");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("storm Biological");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("torm Biological:");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("orm Biological: ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("rm Biological: M");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("m Biological: Mo");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print(" Biological: Mon");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("Biological: Moni");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("iological: Monit");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("ological: Monito");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("logical: Monitor");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("ogical: Monitore");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("gical: Monitoreo");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("ical: Monitoreo ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("cal: Monitoreo A");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("al: Monitoreo Am");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("l: Monitoreo Amb");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print(": Monitoreo Ambi");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print(" Monitoreo Ambie");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("Monitoreo Ambien");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("onitoreo Ambient");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("nitoreo Ambienta");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("itoreo Ambiental");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("toreo Ambiental ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("oreo Ambiental S");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("reo Ambiental Se");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("eo Ambiental Seg");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("o Ambiental Segu");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print(" Ambiental Segur");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print(" Ambiental Seguro");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("Ambiental Seguro ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("mbiental Seguro  ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("biental Seguro   ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("biental Seguro  ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("iental Seguro   ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("ental Seguro    ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("ntal Seguro     ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("tal Seguro      ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("al Segu         ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("l Seguro      ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print(" Seguro        ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("Seguro        ");
delay(550);
lcd.setCursor (0,0);
lcd.print("    MB: MAS     ");
lcd.setCursor (0,1);
lcd.print("eguro        ");
delay(550);

}
}
